name: Deploy the code
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Install sshpass
      run: sudo apt-get install sshpass
 
    - name: Copy code to IIS server
      run: |
        echo "Copying code to IIS server"
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/c/inetpub
      env:
        TZ: "Etc/UTC"
