on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
 
    - name: Build project
      run: dotnet build --configuration Release
 
    - name: Publish project
      run: dotnet publish --configuration Release --output ./output
 
    - name: Create artifact with timestamp
      run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        zip -r "artifact-$timestamp.zip" ./output
      env:
        TZ: "Etc/UTC"
 
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: artifact-*.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
 
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
 
    - name: Install sshpass
      run: sudo apt-get install sshpass
 
    - name: Deploy to IIS
      run: |
        artifact=$(ls artifact-*.zip)
        echo "Deploying $artifact to IIS server"
        sshpass -p "${{ secrets.RDP_PASSWORD }}" scp $artifact ${{ secrets.RDP_USER }}@${{ secrets.RDP_SERVER }}:/c/inetpub
      env:
        TZ: "Etc/UTC"
